project_id = "akqldesakmcroydbgkbe"

[functions.get-active-coupons]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.notify-10cliks]
verify_jwt = false

[functions.send-promotion-email]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.expire-coupons]
verify_jwt = false

[functions.get-queue-info]
verify_jwt = false

[functions.send-queue-email]
verify_jwt = false
